In [1]:
import numpy as np

In [2]:
myarray = np.random.randint(1, 1000, 10)

In [3]:
print(myarray)

[960 650 970 989 606 982   1 942  48 335]


In [7]:
def find_smallest_number(array):
    smallest_number = None
    for number in array:
        if smallest_number == None or number < smallest_number:
            smallest_number = number
    return smallest_number

In [9]:
find_smallest_number(myarray)

1

In [12]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
M = np.ones((2, 3))

In [14]:
a = np.arange(3)

In [16]:
print(M+a)

[[1. 2. 3.]
 [1. 2. 3.]]


In [17]:
print(a)

[0 1 2]


In [22]:
type(a[0])

numpy.int64